<a href="https://colab.research.google.com/github/singhvarun404/AIML_2020/blob/master/Aug_10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
date = 10
topic = "numpy"
print("August: {} \nTopic: {}".format(date,topic))

August: 10 
Topic: numpy


In [2]:
import numpy as np

**Just depicting some numpy array below:**

In [3]:
one_d_array = np.array([1,2,3,4,5])
print(one_d_array)
type(one_d_array)

[1 2 3 4 5]


numpy.ndarray

In [4]:
two_d_array = np.array([[1,3,5,7],[2,4,6,8]])
print("Two dimensional array:\n", two_d_array)
print("Array shape:",two_d_array.shape)
print("Array size:",two_d_array.size)
print("Array dimension",two_d_array.ndim)
print("No. of elements:",len(two_d_array))

Two dimensional array:
 [[1 3 5 7]
 [2 4 6 8]]
Array shape: (2, 4)
Array size: 8
Array dimension 2
No. of elements: 2


In [5]:
three_d_array = np.array([[[1,4,7,10],[2,5,8,11],[3,6,9,12]],[[2,8,14,20],[4,10,16,22],[6,12,18,24]]])
print("Three dimensional array: \n{}".format(three_d_array))
print("Array shape:",three_d_array.shape)
print("Array size:",three_d_array.size)
print("Array dimension:",three_d_array.ndim)
print("No. of elements:",len(three_d_array))

Three dimensional array: 
[[[ 1  4  7 10]
  [ 2  5  8 11]
  [ 3  6  9 12]]

 [[ 2  8 14 20]
  [ 4 10 16 22]
  [ 6 12 18 24]]]
Array shape: (2, 3, 4)
Array size: 24
Array dimension: 3
No. of elements: 2


**Accessing arrays using indexing:**

In [6]:
temp_array = np.array([[1,2,3,4,5],
                       [2,4,6,5,7],
                       [5,6,8,3,2],
                       [50,60,80,30,20],
                       [5,60,8,30,2]])

In [7]:
print("Third element: ",temp_array[3])

Third element:  [50 60 80 30 20]


In [8]:
print("Entire array\n", temp_array[:])

Entire array
 [[ 1  2  3  4  5]
 [ 2  4  6  5  7]
 [ 5  6  8  3  2]
 [50 60 80 30 20]
 [ 5 60  8 30  2]]


In [9]:
print("Fourth column", temp_array[:,3])

Fourth column [ 4  5  3 30 30]


In [10]:
print(temp_array.size)
print(temp_array.mean())
print(temp_array.sum())
print(temp_array.sum()/temp_array.size)

25
16.32
408
16.32


In [11]:
print(temp_array)
print("Adding across vertical-axis:",temp_array.sum(axis=0))
print("Adding across horizontal-axis:",temp_array.sum(axis=1))

[[ 1  2  3  4  5]
 [ 2  4  6  5  7]
 [ 5  6  8  3  2]
 [50 60 80 30 20]
 [ 5 60  8 30  2]]
Adding across vertical-axis: [ 63 132 105  72  36]
Adding across horizontal-axis: [ 15  24  24 240 105]


In [30]:
print("Current array:\n", temp_array)
print("Current shape of array:", temp_array.shape)

Current array:
 [[ 1  2  3  4  5]
 [ 2  4  6  5  7]
 [ 5  6  8  3  2]
 [50 60 80 30 20]
 [ 5 60  8 30  2]]
Current shape of array: (5, 5)


In [34]:
temp_array = temp_array.reshape(1,25)
print("Reshaped array:\n", temp_array)
print("Shape of reshaped array:", temp_array.shape)

Reshaped array:
 [[ 1  2  3  4  5  2  4  6  5  7  5  6  8  3  2 50 60 80 30 20  5 60  8 30
   2]]
Shape of reshaped array: (1, 25)


**Generating range in numpy:**

In [13]:
start = 2
stop = 100
total_num = 50
t_range = np.linspace(start,stop,total_num)
print(t_range)
print(type(t_range))
print(t_range.dtype)
print(t_range.shape)

[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.
  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.
  86.  88.  90.  92.  94.  96.  98. 100.]
<class 'numpy.ndarray'>
float64
(50,)


In [37]:
t2_range = np.arange(start,stop,2)
print(t2_range)
print(t2_range.dtype)
print(t2_range.shape)
t2_range = t2_range.reshape(7,7)
print(t2_range)
print(t2_range.shape)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]
int64
(49,)
[[ 2  4  6  8 10 12 14]
 [16 18 20 22 24 26 28]
 [30 32 34 36 38 40 42]
 [44 46 48 50 52 54 56]
 [58 60 62 64 66 68 70]
 [72 74 76 78 80 82 84]
 [86 88 90 92 94 96 98]]
(7, 7)


**Generating randomness:**

In [15]:
random_no = np.random.randint(100)
print(random_no)
random_no = np.random.randint(100)
print(random_no)

35
31


In [22]:
np.random.seed(0)  
print("Random array: \n",np.random.randint(1,100,(5,5)))

Random array: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]


In [21]:
np.random.seed(0)
print("Same random array as same seed is used: \n",np.random.randint(1,100,(5,5)))
np.random.seed(3)
print("Different random array as seed is changed: \n",np.random.randint(1,100,(5,5)))

Same random array as same seed is used: 
 [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]
Different random array as seed is changed: 
 [[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 97 21 45]
 [94 40 15 27 82]
 [91 23 67  3 64]]


In [23]:
np.random.random(5)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [24]:
np.random.random((5,5))

array([[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672]])